### ISSUE TITLE
'CUDA_VISIBLE_DEVICES' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by IntrovertsBedroom** [mit-han-lab/streaming-llm#11]
It kept saying "'CUDA_VISIBLE_DEVICES' is not recognized as an internal or external command, operable program or batch file." When I tried running the command "CUDA_VISIBLE_DEVICES=0 python examples/run_streaming_llama.py  --enable_streaming".

I was able to get it working by using the command "set CUDA_VISIBLE_DEVICES=0 && python examples/run_streaming_llama.py --enable_streaming"

**Comment by Beomi** [comment]
The issue might be that you're using Windows OS instead of Linux. 
On Linux, the command provided is indeed the correct one.
