### ISSUE TITLE
wrong

### ISSUE THREAD

**Issue by QingChengLineOne** [mit-han-lab/streaming-llm#22]
![image](https://github.com/mit-han-lab/streaming-llm/assets/111961874/48bcae92-13b6-4604-9d7b-94d818053749)

**Comment by Guangxuan-Xiao** [comment]
Hi, could you provide your PyTorch version?

**Comment by QingChengLineOne** [comment]
oh,thank you. I have sloved this problem. I change my pytorch version and run success.



---Original---
From: "Guangxuan ***@***.***&gt;
Date: Thu, Oct 12, 2023 05:58 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [mit-han-lab/streaming-llm] wrong (Issue #22)




 
Hi, could you provide your PyTorch version?

**Comment by QingChengLineOne** [comment]
ok, I will do it



---Original---
From: "Guangxuan ***@***.***&gt;
Date: Thu, Oct 12, 2023 09:47 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [mit-han-lab/streaming-llm] wrong (Issue #22)




 
Closed #22 as completed.
