### ISSUE TITLE
测试了没有提速哇，咋回事呢？

### ISSUE THREAD

**Issue by xxm1668** [mit-han-lab/streaming-llm#30]

**Comment by Guangxuan-Xiao** [comment]
Hi, what's your baseline in comparison?

**Comment by xxm1668** [comment]
Seq2SeqPeftTrainer.predict, withi this

**Comment by Guangxuan-Xiao** [comment]
The speedup is compared with the sliding window with a recomputation baseline, in which you input a text truncated with the same text length into the model and only predict one token.
