### ISSUE TITLE
Can support to Qwen14B?

### ISSUE THREAD

**Issue by ChenTao98** [mit-han-lab/streaming-llm#34]
Streaming-llm is a good work for llm to solve long-text generation problem. 

And I hope the streaming-llm can supported [Qwen-14B](https://github.com/QwenLM/Qwen) in the future, which achieves a good performance in Chinese generation. 

Thanks for your work.

**Comment by tomaarsen** [comment]
Support for Qwen is possible, see e.g. here: https://github.com/tomaarsen/attention_sinks/pull/15
