### ISSUE TITLE
Support for MPT 

### ISSUE THREAD

**Issue by DungNasSa10** [mit-han-lab/streaming-llm#6]
Will you release the code for MPT? I saw in your paper the result of MPT but I didn't find the code for MPT in [https://github.com/mit-han-lab/streaming-llm/tree/main/streaming_llm/pos_shift](https://github.com/mit-han-lab/streaming-llm/tree/main/streaming_llm/pos_shift).

**Comment by Guangxuan-Xiao** [comment]
We do support MPT :). https://github.com/mit-han-lab/streaming-llm/blob/main/streaming_llm/enable_streaming_llm.py#L12
