### ISSUE TITLE
window_size attention pretrain 

### ISSUE THREAD

**Issue by wawpaopao** [mit-han-lab/streaming-llm#7]
Thanks for your great job!
I want to ask how to use initial token like section 3.3 to pretrain a gpt-like model ,which use window_size attention...For example, the input length is 2048 while the window_size is 512,query and key will be shaped like (batch,len/window_size,window_size,dimension), should I append the initial token into every q,make the shape (batch,len/window_seze,window_size+1,dimension)?

**Comment by Guangxuan-Xiao** [comment]
GPT-like models use dense attention while pre-training. You can prepend a BOS token to each sample or forcefully set all inputs' first token to a specific BOS token.

**Comment by wawpaopao** [comment]
thanks! but in the original training settings ,for example, Pythia, doesn't every pre-training sample already start with a BOS token ?

**Comment by Guangxuan-Xiao** [comment]
Pythia, MPT, and Falcon didn't. While Llama has a BOS, it's at paragraph level, not chunk level, which means that after text chunking, the first token of each chunk is not necessary (mostly not) the BOS token.
